### ISSUE TITLE
Google Play Games Dektop

### ISSUE THREAD

**Issue by SimonIT** [MrStahlfelge/gdx-gamesvcs#21]
Hello,

I've integrated gdx-gamesvcs with Google Play Games in my project and it works on android. But on desktop, I'm getting this messages on start:
```
Feb 09, 2018 12:52:05 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNUNG: unable to change permissions for everybody: C:\Users\simon\.store\Turban Guy
Feb 09, 2018 12:52:05 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNUNG: unable to change permissions for owner: C:\Users\simon\.store\Turban Guy
```

And this messages when I try to log in:
gsShowErrorToUser `errorLoginFailed Request to Google API failed.`

I'm using gamesvcsVersion 0.2.2 and gdxVersion 1.9.8.
Thanks for your help.

**Comment by mgsx-dev** [comment]
Hi, warnings are not an issue, it should work. Maybe your problem is elsewhere.

Could you try to set log level to Application.LOG_DEBUG for both your gdx app and the GpgsClient (calling GpgsClient setLogLevel method) to see what's happening ?

Maybe you could provide some of your code to see where your issue is ?

**Comment by SimonIT** [comment]
This is the exception:
`com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at de.golfgl.gdxgamesvcs.GpgsClient.waitForUserAuthorization(GpgsClient.java:265)
	at de.golfgl.gdxgamesvcs.GpgsClient.access$100(GpgsClient.java:67)
	at de.golfgl.gdxgamesvcs.GpgsClient$2.run(GpgsClient.java:305)
	at java.lang.Thread.run(Thread.java:748)`

This is the code from DesktopLauncher:
`new LwjglApplication(new TurbanGuyGame() {
            @Override
            public void create() {
                gsClient = new GpgsClient().initialize("Turban Guy",
                        Gdx.files.internal("gpgs-client_secret.json"), true);
                super.create();
            }
        }, config);`

The gpgs-client_secret.json looks like this:
`{
  "installed": {
    "client_id": "ID",
    "project_id": "ID",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "Secret",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}`

I've downloaded the JSON from https://console.developers.google.com/apis/credentials/oauthclient
I changed the client_id, project_id  and client_scecret before posting

**Comment by mgsx-dev** [comment]
please read the javadoc here : https://github.com/MrStahlfelge/gdx-gamesvcs/blob/master/desktop-gpgs/src/de/golfgl/gdxgamesvcs/GpgsClient.java#L184

your json structure just needs client_id and client_secret, maybe the extra configuration is messing up ?

**Comment by SimonIT** [comment]
It changes nothing, now this is the json:
`{
  "installed": {
    "client_id": "ID",
    "client_secret": "ID"
  }
}`

**Comment by mgsx-dev** [comment]
and about the OAuth type ?

**Comment by SimonIT** [comment]
Yes (see the last answer)

**Comment by mgsx-dev** [comment]
did you clear your Oauth token (local file in <user>/.store/Turban Guy) to re-authorized throw your browser after changing the credentials ?

**Comment by SimonIT** [comment]
After clearing the Oauth token is it working, thanks

**Comment by mgsx-dev** [comment]
Cool ! you can close the issue then ;-)
