### ISSUE TITLE
Runtime error java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;

### ISSUE THREAD

**Issue by kloylar** [MrStahlfelge/gdx-gamesvcs#41]
When using gdx-gamesvcs in junction with "com.google.firebase:firebase-analytics:17.4.4" or posterior 
then code compile but generate a runtime error at the line 

    game.gsClient = new GpgsClient().initialize(this,false);

with firebase analytics version 17.4.3 or prior the code works

Error log..............

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mygdx.game, PID: 22977
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
        at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source)
        at de.golfgl.gdxgamesvcs.GpgsClient.initialize(GpgsClient.java:117)
        at com.mygdx.game.AndroidLauncher.onCreate(AndroidLauncher.java:17)
        at android.app.Activity.performCreate(Activity.java:6285)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.mygdx.game-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mygdx.game-2/lib/arm, /data/app/com.mygdx.game-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source) 
        at de.golfgl.gdxgamesvcs.GpgsClient.initialize(GpgsClient.java:117) 
        at com.mygdx.game.AndroidLauncher.onCreate(AndroidLauncher.java:17) 
        at android.app.Activity.performCreate(Activity.java:6285) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v4.util.ArrayMap
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
D/FBAudienceNetwork: SDK dex loading time: 1514

**Comment by MrStahlfelge** [comment]
Since the problem is telated to support classes, I would recommend to activate jetifier in your project. That will probably solve the problem.

**Comment by MrStahlfelge** [comment]
Closed due to no reaction
