### ISSUE TITLE
GameCenter: UnsupportedOperationException on loadGameState()

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/gdx-gamesvcs#42]
Calling loadGameState() when more snapshots are available results in `UnsupportedOperationException`

java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:404)
	at java.util.AbstractList.add(AbstractList.java:425)
	at org.robovm.apple.foundation.NSArray.add(NSArray.java:267)
	at de.golfgl.gdxgamesvcs.GameCenterClient$7.invoke(GameCenterClient.java:287)
	at de.golfgl.gdxgamesvcs.GameCenterClient$7.invoke(GameCenterClient.java:261)

`NSArray` does not support adding elements.

**Comment by MrStahlfelge** [comment]
NSMutableArray should be used, or Java Array converted to NSArray.
