### ISSUE TITLE
Crash on first start after deleting data

### ISSUE THREAD

**Issue by SakiiCode** [MrStahlfelge/gdx-gamesvcs#51]
```
10-16 20:52:17.750 19029 19053 E Volley  : [5773] bmi.a: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/************?language=hu-HU&platformType=ANDROID
10-16 20:52:18.491 19029 19500 E SignInPerformer-6: Failed to load game for package [****************] [CONTEXT service_id=1 ]
10-16 20:52:18.507 18146 18146 E AndroidRuntime: FATAL EXCEPTION: main
10-16 20:52:18.507 18146 18146 E AndroidRuntime: Process: ******, PID: 18146
10-16 20:52:18.507 18146 18146 E AndroidRuntime: java.lang.IllegalStateException: A fatal developer error has occurred. Class name: zzf. Start service action: com.google.android.gms.games.service.START. Service Descriptor: com.google.android.gms.games.internal.IGamesService. 
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
10-16 20:52:18.507 18146 18146 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Steps to reproduce:
1. Connect the app to Play Games
2. Save data to the cloud
3. Open Play Games and delete app data there
4. Open the game
5. Crash

Not really a big deal though because everything works after restarting the game, just an edge case.
I don't know if even fixable

**Comment by MrStahlfelge** [comment]
My guess is your game does not check login state before accessing the save game data.
